language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - pip install cython
install:
  - sudo apt-get install python-vtk python-qt4 python-qt4-dev python-sip python-qt4-gl libqt4-scripttools swig
  - pip install -r dev_requirements.txt --use-mirrors
  - python setup.py develop
script:
  unit2 discover -v
notifications:
  email:
    - travis-ci@enthought.com
